language: python

sudo: false
sudo: required

env:
   matrix:
      - LUA="lua=5.1"
      - LUA="lua=5.2"
      - LUA="lua=5.3"
      - LUA="luajit=2.0"
      - LUA="luajit=2.1"

branches:
   only:
      - master

before_install:
   - pip install hererocks
   - pip install tap.py
   - hererocks base -r^ --$LUA
   - export PATH=$PATH:$PWD/base/bin
   - luarocks install tapered
   - luarocks install lzt

script:
   - lzt luapath > luapath.sh
   - lzt testenv > testenv.sh
   - source luapath.sh
   - source testenv.sh
   - tappy *.tap

notifications:
   email:
      on_success: change
      on_failure: always
