= mint

[source,lua]
----
function mint( template [, ename] ) --> ( sandbox ) --> expstr, err
----

== Description

Expand the Lua code contained in the _template_.
The following pattern in the _template_ will be expanded:

`@{luaexp}`::
Will be substituted with the result of the Lua expression.

`@{{luastm}}`::
Embeds the Lua statement. This allow to mix Lua code and verbatim text.

The function works in two steps:

1. returns a generator function that takes a table(_sandbox_)
2. returns the generator function the expanded string(_expstr_)

== Parameters

template::
The string that should be expanded.

ename::
The Lua code will have access to a global with this name.
It will be a function that will append its first argument to the template output
string.
This parameter is optional, the default value is +_o+.

sandbox::
The contents of this table will be injected into the environment of the Lua
code (both expressions and statements). This allows you to pass parameters to
the template.

== Return Values

expstr::
The resulting expanded text or *nil* if an error occurse.

err::
A message if an error occurse, otherwise *nil*.

== Code

[source,lua]
----
include::mint.lua[]
----

== Examples

[source,lua]
----
include::mint.ex1.lua[]
----

== Inspired by

* https://github.com/leafo/etlua

