local t = require( "taptest" )
local ltrim = require( "ltrim" )

t( ltrim( "" ), "" )
t( ltrim( " " ), "" )
t( ltrim( "  " ), "" )
t( ltrim( "a" ), "a" )
t( ltrim( " a" ), "a" )
t( ltrim( "a " ), "a " )
t( ltrim( " a " ), "a " )
t( ltrim( "  a  " ), "a  " )
t( ltrim( " ab cd " ), "ab cd " )
t( ltrim( " \t\r\n\f\va\00b \r\t\n\f\v" ), "a\00b \r\t\n\f\v" )

t()
