local t = require( "taptest" )
local iscntrl = require( "iscntrl" )

local NUL = string.char( 0x00 )
local SOH = string.char( 0x01 )
local STX = string.char( 0x02 )
local ETX = string.char( 0x03 )
local EOT = string.char( 0x04 )
local ENQ = string.char( 0x05 )
local ACK = string.char( 0x06 )
local BEL = string.char( 0x07 )
local BS = string.char( 0x08 )
local HT = string.char( 0x09 )
local LF = string.char( 0x0a )
local VT = string.char( 0x0b )
local FF = string.char( 0x0c )
local CR = string.char( 0x0d )
local SO = string.char( 0x0e )
local SI = string.char( 0x0f )
local DLE = string.char( 0x10 )
local DC1 = string.char( 0x11 )
local DC2 = string.char( 0x12 )
local DC3 = string.char( 0x13 )
local DC4 = string.char( 0x14 )
local NAK = string.char( 0x15 )
local SYN = string.char( 0x16 )
local ETB = string.char( 0x17 )
local CAN = string.char( 0x18 )
local EM = string.char( 0x19 )
local SUB = string.char( 0x1a )
local ESC = string.char( 0x1b )
local FS = string.char( 0x1c )
local GS = string.char( 0x1d )
local RS = string.char( 0x1e )
local US = string.char( 0x1f )

local DEL = string.char( 0x7f )

t( iscntrl( NUL..SOH..DEL..ETB ), true )

res, pos = iscntrl( "" )
t( res, false )
t( pos, 0 )

res, pos = iscntrl( NUL..SOH.."1"..DEL )
t( res, false )
t( pos, 3 )

t()
